// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wtlrksfzbgsjqnxwnmar.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind0bHJrc2Z6YmdzanFueHdubWFyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2NjY2OTYsImV4cCI6MjA1OTI0MjY5Nn0.Moy50p8jKmElpVa7h9S-eOIbDF8T-S9ZzOBR2Y-c1l8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);